### ISSUE TITLE
Compilation for no_std fails due to httparse dependency

### ISSUE THREAD

**Issue by AnthonyGrondin** [ivmarkov/edge-net#1]
Compilation for `no_std` targets fails due to the httparse dependency which enables `std` by default.

https://github.com/ivmarkov/edge-net/blob/233f632dd40e86df2783df7676f967aa40bcb876/Cargo.toml#L26

### httparse Cargo.toml: 
```toml
[features]
default = ["std"]
std = []
```
